# Generated by Django 5.1.7 on 2025-04-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='is_slider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
