# Generated by Django 5.1.7 on 2025-04-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsitem_is_slider_alter_newsitem_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='image',
            field=models.ImageField(upload_to='news_images/'),
        ),
    ]
